### ISSUE TITLE
ModuleNotFoundError: No module named 'libs.sepconv._ext.cunnex._cunnex'

### ISSUE THREAD

**Issue by repers** [martkartasev/sepconv#30]
Hi, I have tried to get the code running however I get this:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rf/sepconv/src/main.py", line 16, in <module>
    from src.model import Net
  File "/home/rf/sepconv/src/model.py", line 10, in <module>
    from libs.sepconv.SeparableConvolution import SeparableConvolution
  File "/home/rf/sepconv/libs/sepconv/SeparableConvolution.py", line 8, in <module>
    import libs.sepconv._ext.cunnex
  File "/home/rf/sepconv/libs/sepconv/_ext/cunnex/__init__.py", line 3, in <module>
    from ._cunnex import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'libs.sepconv._ext.cunnex._cunnex'

I have tested this on 3 different systems with the required software version including cuda installed, searching up this issue has yielded no useful answers

Any suggestions as to what's going wrong?
Thanks in advance

**Comment by shishichang** [comment]
> Hi, I have tried to get the code running however I get this:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/rf/sepconv/src/main.py", line 16, in 
> from src.model import Net
> File "/home/rf/sepconv/src/model.py", line 10, in 
> from libs.sepconv.SeparableConvolution import SeparableConvolution
> File "/home/rf/sepconv/libs/sepconv/SeparableConvolution.py", line 8, in 
> import libs.sepconv._ext.cunnex
> File "/home/rf/sepconv/libs/sepconv/_ext/cunnex/**init**.py", line 3, in 
> from ._cunnex import lib as _lib, ffi as _ffi
> ModuleNotFoundError: No module named 'libs.sepconv._ext.cunnex._cunnex'
> 
> I have tested this on 3 different systems with the required software version including cuda installed, searching up this issue has yielded no useful answers
> 
> Any suggestions as to what's going wrong?
> Thanks in advance

you should install sepconv in ./lib/sepconv first.

**Comment by wayne2tech** [comment]
> > Hi, I have tried to get the code running however I get this:
> > Traceback (most recent call last):
> > File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/home/rf/sepconv/src/main.py", line 16, in
> > from src.model import Net
> > File "/home/rf/sepconv/src/model.py", line 10, in
> > from libs.sepconv.SeparableConvolution import SeparableConvolution
> > File "/home/rf/sepconv/libs/sepconv/SeparableConvolution.py", line 8, in
> > import libs.sepconv._ext.cunnex
> > File "/home/rf/sepconv/libs/sepconv/_ext/cunnex/**init**.py", line 3, in
> > from ._cunnex import lib as _lib, ffi as _ffi
> > ModuleNotFoundError: No module named 'libs.sepconv._ext.cunnex._cunnex'
> > I have tested this on 3 different systems with the required software version including cuda installed, searching up this issue has yielded no useful answers
> > Any suggestions as to what's going wrong?
> > Thanks in advance
> 
> you should install sepconv in ./lib/sepconv first.

![image](https://user-images.githubusercontent.com/56107092/143211992-d8582366-950e-43f1-b1d8-eb969ef44d0a.png)
When I execute the bash file, there still seems to be some problems，
